[package]
name = "shell"
version = "0.1.0"
edition = "2021"

[dependencies]
#sysinfo = "0.31.4"
#os_pipe = "1.0"
#libc = "0.2.170"
#ascii-to-hex = "0.1.1"
sysinfo.workspace=true
os_pipe.workspace=true
libc.workspace=true
ascii-to-hex.workspace=true
